import Head from "next/head";
import FormComponent from "../../components/RegisterForm";
import Navbar from "../../components/Navbar";
import axios from "axios";
import nookies  from 'nookies';

export { default as getServerSideProps } from "../../lib/ServerProps"


export default function Home(props: any) {

  const {user: {username}} = props;

  return (
    <div>
      <Head>
        <title>Odesey Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar isAuthenticated={props.isAuthenticated}/>

        <div className="p-4 ml-4">

        <h2> Welcome {username} </h2>
        </div>
        
    </div>
  );
}


