import Head from "next/head";
import FormComponent from "../../components/RegisterForm";
import Navbar from "../../components/Navbar";
import axios from "axios";
import nookies  from 'nookies';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Odesey Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <p> Sensitive infor</p>
        
    </div>
  );
}

// export const getServerSideProps = async (context: any) => {
//     const cookies = nookies.get(context);
//     let validToken;
  
//     if (cookies?.jwt) {
      
//     }
  
//     if (!validToken) {
//       return {
//         redirect: {
//           permanent: false,
//           destination: "/",
//         },
//       };
//     }
  
//     return {
//       props: {
        
//       },
//     };
//   };
