import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1 className="text-3xl font-sans font-bold underline">
      Odesey Front end
    </h1>
      </main>

     
    </div>
  )
}
