import Head from "next/head";
import FormComponent from "../components/RegisterForm";
import Navbar from "../components/Navbar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Odesey Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <p> Landing page </p>
        
    </div>
  );
}
